'use client';
import {useEffect,useState} from 'react';
import {createPortal} from 'react-dom';
import ProjectManager from './ProjectManager';

export default function BackgroundTools(){
 const [hosts,setHosts]=useState<{canvas:HTMLElement;panel:HTMLElement}|null>(null);
 const [enabled,setEnabled]=useState(false),[blur,setBlur]=useState(0),[brightness,setBrightness]=useState(100),[saturation,setSaturation]=useState(100),[contrast,setContrast]=useState(100),[speed,setSpeed]=useState(16);
 const [colors,setColors]=useState(['#69bfc9','#d9cb39','#bc6474']);
 useEffect(()=>{const canvas=document.querySelector<HTMLElement>('.canvas'),panel=document.querySelector<HTMLElement>('.inspector');if(canvas&&panel)setHosts({canvas,panel})},[]);
 useEffect(()=>{if(!hosts)return;hosts.canvas.style.setProperty('--background-filter',`blur(${blur}px) brightness(${brightness}%) saturate(${saturation}%) contrast(${contrast}%)`);hosts.canvas.style.setProperty('--background-size',String(1+blur/150));return()=>{hosts.canvas.style.removeProperty('--background-filter');hosts.canvas.style.removeProperty('--background-size')}},[hosts,blur,brightness,saturation,contrast]);
 if(!hosts)return null;
 return <><ProjectManager/>{createPortal(<section className="inspector-section background-tools"><h3>Background studio</h3><p>Effects apply only to the background image or video.</p>{([{name:'Blur',value:blur,set:setBlur,min:0,max:60,unit:'px'},{name:'Brightness',value:brightness,set:setBrightness,min:0,max:200,unit:'%'},{name:'Saturation',value:saturation,set:setSaturation,min:0,max:200,unit:'%'},{name:'Contrast',value:contrast,set:setContrast,min:0,max:200,unit:'%'}]).map(c=><label key={c.name}>{c.name} · {c.value}{c.unit}<input aria-label={`Background ${c.name}`} type="range" min={c.min} max={c.max} value={c.value} onChange={e=>c.set(+e.target.value)}/></label>)}<button onClick={()=>{setBlur(0);setBrightness(100);setSaturation(100);setContrast(100)}}>Reset background effects</button><label><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/> Dream lights · seamless loop</label><p>Turn on to place animated colour lights over the background, behind your cover.</p><div className="dream-colors">{colors.map((color,i)=><input aria-label={`Dream light colour ${i+1}`} key={i} type="color" value={color} onChange={e=>setColors(cs=>cs.map((c,j)=>j===i?e.target.value:c))}/>)}</div><label>Loop duration · {speed}s<input aria-label="Dream loop duration" type="range" min="4" max="40" value={speed} onChange={e=>setSpeed(+e.target.value)}/></label></section>,hosts.panel)}{enabled&&createPortal(<div className="dream-background" aria-hidden="true" style={{'--dream-time':`${speed}s`} as React.CSSProperties}>{colors.map((color,i)=><i key={i} style={{background:color,animationDelay:`-${i*speed/3}s`}}/>)}</div>,hosts.canvas)}</>;
}
