'use client';
import {useEffect,useState,useRef} from 'react';
import {renderVideo} from './renderVideo';


export type ExportPreset={width:number;height:number;fps:24|30|60;quality:'standard'|'high'|'master';duration:number;format:'mp4'};
export default function ExportSettings({onClose,audioDuration=0,onRender}:{onClose:()=>void;audioDuration?:number;onRender?:()=>void}){
 const [progress,setProgress]=useState(0);const [preset,setPreset]=useState<ExportPreset>({width:1080,height:1920,fps:30,quality:'high',duration:30,format:'mp4'});const [rendering,setRendering]=useState(false);const [message,setMessage]=useState('');const [detected,setDetected]=useState(audioDuration);const duration=detected||audioDuration;
 useEffect(()=>{const audio=document.querySelector('audio');const sync=()=>{if(audio&&Number.isFinite(audio.duration)&&audio.duration>0)setDetected(audio.duration)};sync();audio?.addEventListener('loadedmetadata',sync);return()=>audio?.removeEventListener('loadedmetadata',sync)},[]);useEffect(()=>{if(duration>0)setPreset(p=>({...p,duration:Math.min(600,Math.max(1,Math.round(duration)))}))},[duration]);
 const cancel=useRef<AbortController|null>(null);
 useEffect(()=>()=>cancel.current?.abort(),[]);
 const render=async()=>{if(rendering)return;const controller=new AbortController();cancel.current=controller;setRendering(true);setProgress(0);try{const blob=await renderVideo(preset,(n,m)=>{setProgress(Math.round(n));setMessage(m)},controller.signal);const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='vage-visualizer.mp4';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);setMessage('MP4 ready — download started')}catch(e){setMessage(e instanceof Error?e.message:String(e))}finally{setRendering(false);cancel.current=null}};
 return <section className="export-settings" aria-label="Export settings"><header><strong>Export video</strong><button disabled={rendering} onClick={onClose}>×</button></header><label>Resolution<select value={`${preset.width}x${preset.height}`} onChange={e=>{const [width,height]=e.target.value.split('x').map(Number);setPreset(p=>({...p,width,height}))}}><option value="1080x1920">1080 × 1920 · Reel / Story</option><option value="1080x1080">1080 × 1080 · Square</option><option value="1920x1080">1920 × 1080 · YouTube</option><option value="2160x2160">2160 × 2160 · 4K Square</option></select></label><label>Frame rate<select value={preset.fps} onChange={e=>setPreset(p=>({...p,fps:Number(e.target.value) as 24|30|60}))}><option value="24">24 fps · Cinematic</option><option value="30">30 fps · Social</option><option value="60">60 fps · Smooth</option></select></label><label>Quality<select value={preset.quality} onChange={e=>setPreset(p=>({...p,quality:e.target.value as ExportPreset['quality']}))}><option value="standard">Standard</option><option value="high">High</option><option value="master">Master</option></select></label><label>Duration (seconds)<input type="number" min="1" max="600" value={preset.duration} onChange={e=>setPreset(p=>({...p,duration:Math.max(1,Number(e.target.value)||1)}))}/></label><button type="button" className="duration-sync" disabled={!duration} onClick={()=>setPreset(p=>({...p,duration:Math.min(600,Math.max(1,Math.round(duration)))}))}>{duration?'Use music duration':'Add music to detect duration'}</button><p>MP4 is rendered from the project canvas at {preset.width}×{preset.height}, {preset.fps} fps.</p>{message&&<p className="export-status" role="status">{message}</p>}{rendering&&<div className="export-progress" aria-label={`Render progress ${progress}%`}><div style={{width:`${progress}%`}}/><span>{progress}% · Rendering…</span></div>}<button className="export-render" type="button" onClick={render} disabled={rendering}>{rendering?'Rendering…':'Render MP4'}</button>{rendering&&<button type="button" onClick={()=>cancel.current?.abort()}>Cancel render</button>}</section>;
}
