'use client';
import {useEffect,useState} from 'react';
import {FFmpeg} from '@ffmpeg/ffmpeg';
import {fetchFile} from '@ffmpeg/util';
const toBlobURL=async(url:string,_mime:string)=>url;
export type ExportPreset={width:number;height:number;fps:24|30|60;quality:'standard'|'high'|'master';duration:number;format:'mp4'};
export default function ExportSettings({onClose,audioDuration=0,onRender}:{onClose:()=>void;audioDuration?:number;onRender?:()=>void}){
 const [preset,setPreset]=useState<ExportPreset>({width:1080,height:1920,fps:30,quality:'high',duration:30,format:'mp4'});const [rendering,setRendering]=useState(false);const [message,setMessage]=useState('');const [detected,setDetected]=useState(audioDuration);const duration=detected||audioDuration;
 useEffect(()=>{const audio=document.querySelector('audio');const sync=()=>{if(audio&&Number.isFinite(audio.duration)&&audio.duration>0)setDetected(audio.duration)};sync();audio?.addEventListener('loadedmetadata',sync);return()=>audio?.removeEventListener('loadedmetadata',sync)},[]);useEffect(()=>{if(duration>0)setPreset(p=>({...p,duration:Math.min(600,Math.max(1,Math.round(duration)))}))},[duration]);
 const render=async()=>{setRendering(true);setMessage('Rendering MP4…');onRender?.();try{const source=document.querySelector<HTMLElement>('.canvas');if(!source)throw Error('Canvas not found');const canvas=document.createElement('canvas');canvas.width=preset.width;canvas.height=preset.height;const ctx=canvas.getContext('2d')!;const draw=()=>{ctx.fillStyle=getComputedStyle(source).backgroundColor||'#11130f';ctx.fillRect(0,0,canvas.width,canvas.height);const sx=canvas.width/source.clientWidth,sy=canvas.height/source.clientHeight;ctx.save();ctx.scale(sx,sy);const base=source.getBoundingClientRect();source.querySelectorAll<HTMLElement>('.canvas-background,.cover,.canvas-title,.canvas-artist,.canvas-text').forEach(el=>{const r=el.getBoundingClientRect();const x=r.left-base.left,y=r.top-base.top;ctx.globalAlpha=Number(getComputedStyle(el).opacity)||1;if(el instanceof HTMLImageElement&&el.complete)ctx.drawImage(el,x,y,r.width,r.height);else if(el instanceof HTMLVideoElement)try{ctx.drawImage(el,x,y,r.width,r.height)}catch{}else{ctx.fillStyle=getComputedStyle(el).color||'#fff';ctx.font=`${getComputedStyle(el).fontWeight} ${getComputedStyle(el).fontSize} ${getComputedStyle(el).fontFamily}`;ctx.fillText(el.textContent||'',x,y+r.height*.75)}});ctx.restore()};draw();const stream=canvas.captureStream(preset.fps);const mime=MediaRecorder.isTypeSupported('video/webm;codecs=vp9')?'video/webm;codecs=vp9':MediaRecorder.isTypeSupported('video/webm')?'video/webm':'';const recorder=new MediaRecorder(stream,mime?{mimeType:mime}:undefined);const chunks:BlobPart[]=[];recorder.ondataavailable=e=>e.data.size&&chunks.push(e.data);const stopped=new Promise<void>(r=>recorder.onstop=()=>r());recorder.start();await new Promise(r=>setTimeout(r,preset.duration*1000));recorder.stop();await stopped;const ffmpeg=new FFmpeg();await ffmpeg.load({coreURL:await toBlobURL('/ffmpeg/ffmpeg-core.js','text/javascript'),wasmURL:await toBlobURL('/ffmpeg/ffmpeg-core.wasm','application/wasm')});await ffmpeg.writeFile('input.webm',await fetchFile(new Blob(chunks,{type:'video/webm'})));await ffmpeg.exec(['-i','input.webm','-c:v','libx264','-pix_fmt','yuv420p','-movflags','faststart','output.mp4']);const data=await ffmpeg.readFile('output.mp4');const blob=new Blob([new Uint8Array(data as Uint8Array)],{type:'video/mp4'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='vage-visualizer.mp4';link.click();URL.revokeObjectURL(url);setMessage('MP4 آماده شد و دانلود شد.')}catch(error){console.error(error);setMessage('رندر انجام نشد؛ کنسول مرورگر را بررسی کن.')}finally{setRendering(false)}};
 return <section className="export-settings" aria-label="Export settings"><header><strong>Export video</strong><button onClick={onClose}>×</button></header><label>Resolution<select value={`${preset.width}x${preset.height}`} onChange={e=>{const [width,height]=e.target.value.split('x').map(Number);setPreset(p=>({...p,width,height}))}}><option value="1080x1920">1080 × 1920 · Reel / Story</option><option value="1080x1080">1080 × 1080 · Square</option><option value="1920x1080">1920 × 1080 · YouTube</option><option value="2160x2160">2160 × 2160 · 4K Square</option></select></label><label>Frame rate<select value={preset.fps} onChange={e=>setPreset(p=>({...p,fps:Number(e.target.value) as 24|30|60}))}><option value="24">24 fps · Cinematic</option><option value="30">30 fps · Social</option><option value="60">60 fps · Smooth</option></select></label><label>Quality<select value={preset.quality} onChange={e=>setPreset(p=>({...p,quality:e.target.value as ExportPreset['quality']}))}><option value="standard">Standard</option><option value="high">High</option><option value="master">Master</option></select></label><label>Duration (seconds)<input type="number" min="1" max="600" value={preset.duration} onChange={e=>setPreset(p=>({...p,duration:Math.max(1,Number(e.target.value)||1)}))}/></label><button type="button" className="duration-sync" disabled={!duration} onClick={()=>setPreset(p=>({...p,duration:Math.min(600,Math.max(1,Math.round(duration)))}))}>{duration?'Use music duration':'Add music to detect duration'}</button><p>MP4 is rendered from the project canvas at {preset.width}×{preset.height}, {preset.fps} fps.</p>{message&&<p className="export-status" role="status">{message}</p>}<button className="export-render" type="button" onClick={render} disabled={rendering}>{rendering?'Preparing render…':'Render MP4'}</button></section>;
}
