'use client';
import {useEffect, useRef, useState} from 'react';
import '../timeline.css';

export default function Timeline(){
 const audio=useRef<HTMLAudioElement>(null),video=useRef<HTMLVideoElement>(null);const [audioUrl,setAudioUrl]=useState('');const [videoUrl,setVideoUrl]=useState('');const [aStart,setAStart]=useState(0);const [aEnd,setAEnd]=useState(100);const [vStart,setVStart]=useState(0);const [vEnd,setVEnd]=useState(100);const [duration,setDuration]=useState(100);const [playing,setPlaying]=useState(false);const [loop,setLoop]=useState(true);
 const load=(e:React.ChangeEvent<HTMLInputElement>,kind:'audio'|'video')=>{const f=e.target.files?.[0];if(!f)return;const url=URL.createObjectURL(f);kind==='audio'?setAudioUrl(url):setVideoUrl(url)};
 useEffect(()=>{const el=audio.current;if(!el)return;const sync=()=>{const start=(aStart/100)*duration;const end=(aEnd/100)*duration;if(el.currentTime>=end){if(loop)el.currentTime=start;else{el.pause();setPlaying(false)}}};el.addEventListener('timeupdate',sync);return()=>el.removeEventListener('timeupdate',sync)},[aStart,aEnd,duration,loop]);
 const play=async()=>{if(!audio.current)return;if(audio.current.paused){audio.current.currentTime=(aStart/100)*duration;await audio.current.play();setPlaying(true)}else{audio.current.pause();setPlaying(false)}};
 return <main className="timeline-page"><header><a className="back" href="/">← ادیتور اصلی</a><div className="brand"><span className="brand-mark">V</span><span>واژه <i>Timeline</i></span></div></header><section className="timeline-hero"><p className="eyebrow">MEDIA RANGE EDITOR</p><h1>زمان‌بندی را<br/><em>دقیق کنترل کن.</em></h1><p>برای موزیک و ویدیوی پس‌زمینه، محدوده‌ی مستقل تعریف کن.</p></section><section className="timeline-card"><div className="media-grid"><label className="media-upload"><input type="file" accept="audio/*" onChange={e=>load(e,'audio')}/><strong>♫ موزیک پروژه</strong><span>{audioUrl?'فایل انتخاب شد':'انتخاب فایل صوتی'}</span></label><label className="media-upload"><input type="file" accept="video/*" onChange={e=>load(e,'video')}/><strong>▣ ویدیوی پس‌زمینه</strong><span>{videoUrl?'فایل انتخاب شد':'انتخاب فایل ویدیویی'}</span></label></div><div className="media-stage">{videoUrl?<video ref={video} src={videoUrl} autoPlay loop muted/>:<div className="stage-empty">ویدیوی پس‌زمینه اینجا نمایش داده می‌شود</div>}<div className="stage-label">PREVIEW</div></div><div className="range-section"><div className="range-title"><strong>موزیک</strong><span>{Math.round(aStart)}% تا {Math.round(aEnd)}%</span></div><div className="track-line audio-track"><div className="range-fill" style={{left:`${aStart}%`,right:`${100-aEnd}%`}}/><input aria-label="شروع موزیک" type="range" min="0" max="99" value={aStart} onChange={e=>setAStart(Math.min(+e.target.value,aEnd-1))}/><input aria-label="پایان موزیک" type="range" min="1" max="100" value={aEnd} onChange={e=>setAEnd(Math.max(+e.target.value,aStart+1))}/></div></div><div className="range-section"><div className="range-title"><strong>ویدیوی پس‌زمینه</strong><span>{Math.round(vStart)}% تا {Math.round(vEnd)}%</span></div><div className="track-line video-track"><div className="range-fill" style={{left:`${vStart}%`,right:`${100-vEnd}%`}}/><input aria-label="شروع ویدیو" type="range" min="0" max="99" value={vStart} onChange={e=>setVStart(Math.min(+e.target.value,vEnd-1))}/><input aria-label="پایان ویدیو" type="range" min="1" max="100" value={vEnd} onChange={e=>setVEnd(Math.max(+e.target.value,vStart+1))}/></div></div><div className="timeline-actions"><button className="play-toggle" onClick={play} disabled={!audioUrl}>{playing?'⏸ توقف':'▶ پخش بازه'}</button><label className="loop-toggle"><input type="checkbox" checked={loop} onChange={e=>setLoop(e.target.checked)}/> Loop بازه</label><label>مدت پایه (ثانیه)<input className="duration-input" type="number" min="1" value={duration} onChange={e=>setDuration(Math.max(1,+e.target.value||1))}/></label></div><audio ref={audio} src={audioUrl}/></section></main>
}
